import * as foo from 'foo';
import * as bar from 'bar';
import * as b from 'foo/bar';
import {bye as bb, hello as h} from 'foo/bar';
import {bar} from '../foo/zoo';
import * as foo from './foo';
import {bar} from './foo';
import {zoo} from 'foo-bar';
import * as fb from 'foo-bar';
import {zoo} from '@foo/bar';
import * as fb from '@foo/bar';
import bar from 'foo';
import {zoo} from '@~/foo/bar';
var test_foo;
test_name = 2;
test_foo = true;
export {test_name, test_foo};
